# Generated by Django 5.1.1 on 2026-07-22 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text="Customer's full name.", max_length=100)),
                ('email', models.EmailField(help_text="Customer's contact email address.", max_length=254)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating score out of 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Customer comments.', max_length=1000)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', help_text='Current review lifecycle state.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating'], name='feedback_fe_rating_c20163_idx'), models.Index(fields=['status'], name='feedback_fe_status_35d074_idx')],
            },
        ),
    ]
